"""Generate Cloudflare Worker redirect map from seo/redirects.json.

Why a Worker (not Bulk Redirect Lists): Free plan Bulk Redirects are capped
(~25 URLs). This site has 100+ soft redirects that need real HTTP 301s while
origin stays on GitHub Pages.

Outputs:
  seo/cloudflare/redirects.map.json
  seo/cloudflare/worker.js

Run: python seo/generate_cloudflare_redirects.py
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REDIRECTS_PATH = ROOT / "seo" / "redirects.json"
OUT_DIR = ROOT / "seo" / "cloudflare"
MAP_PATH = OUT_DIR / "redirects.map.json"
WORKER_PATH = OUT_DIR / "worker.js"

SITE_ORIGIN = "https://www.sangkanclean.com"
APEX_HOST = "sangkanclean.com"
WWW_HOST = "www.sangkanclean.com"


def load_path_map() -> dict[str, str]:
    rules = json.loads(REDIRECTS_PATH.read_text(encoding="utf-8"))
    out: dict[str, str] = {}
    for rule in rules:
        src = (rule.get("from") or "").strip()
        dst = (rule.get("to") or "").strip()
        if not src or not dst:
            continue
        if not src.startswith("/"):
            src = "/" + src
        if not dst.startswith("/"):
            dst = "/" + dst
        out[src] = dst
    # Stable folder alias (already soft-redirected in HTML)
    out.setdefault("/blog/", "/blog.html")
    out.setdefault("/blog/index.html", "/blog.html")
    return dict(sorted(out.items()))


WORKER_TEMPLATE = """\
/**
 * Sangkan Clean — HTTP 301 edge redirects (Cloudflare Worker).
 * Generated by seo/generate_cloudflare_redirects.py — do not edit by hand.
 *
 * Origin remains GitHub Pages. This Worker only 301s known paths, then
 * passes everything else through to the same hostname (CF orange-cloud).
 */
const REDIRECTS = __MAP_JSON__;

const WWW_HOST = "__WWW_HOST__";
const APEX_HOST = "__APEX_HOST__";

export default {
  async fetch(request) {
    const url = new URL(request.url);

    // Force apex → www (matches SITE_URL canonical policy)
    if (url.hostname === APEX_HOST) {
      url.hostname = WWW_HOST;
      return Response.redirect(url.toString(), 301);
    }

    const targetPath = REDIRECTS[url.pathname];
    if (targetPath) {
      const dest = new URL(targetPath, "https://" + WWW_HOST);
      dest.search = url.search;
      return Response.redirect(dest.toString(), 301);
    }

    return fetch(request);
  },
};
"""


def main() -> int:
    path_map = load_path_map()
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    MAP_PATH.write_text(
        json.dumps(path_map, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    worker = (
        WORKER_TEMPLATE.replace("__MAP_JSON__", json.dumps(path_map, ensure_ascii=False, indent=2))
        .replace("__WWW_HOST__", WWW_HOST)
        .replace("__APEX_HOST__", APEX_HOST)
    )
    WORKER_PATH.write_text(worker, encoding="utf-8")
    print(f"Wrote {MAP_PATH.relative_to(ROOT)} ({len(path_map)} paths)")
    print(f"Wrote {WORKER_PATH.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
